package com.samsung.android.poc.remotecontroller.eventhandler

import android.util.SparseArray
import com.samsung.android.poc.remotecontroller.R
import com.samsung.android.poc.remotecontroller.datastore.*

object CommandInfo {
    private val CLASS_NAME = CommandInfo::class.java.simpleName
    val rcKeySparseArray = SparseArray<String>()
    fun getKeyById(id: Int): String {
        return rcKeySparseArray[id]
    }

    init {
        rcKeySparseArray.put(
            R.id.rc_volume_up,
            KEY_EVENT_VOL_UP
        )
        rcKeySparseArray.put(
            R.id.rc_volume_down,
            KEY_EVENT_VOL_DOWN
        )
        rcKeySparseArray.put(
            R.id.rc_power,
            KEY_EVENT_POWER
        )
        rcKeySparseArray.put(
            R.id.rc_channel_up,
            KEY_EVENT_CH_UP
        )
        rcKeySparseArray.put(
            R.id.rc_channel_down,
            KEY_EVENT_CH_DOWN
        )
        rcKeySparseArray.put(
            R.id.rc_volume_mute,
            KEY_EVENT_MUTE
        )
        rcKeySparseArray.put(
            R.id.rc_source,
            KEY_EVENT_SOURCE
        )
        rcKeySparseArray.put(
            R.id.rc_smart_hub_extra_img,
            KEY_EVENT_COLOR
        )
        rcKeySparseArray.put(
            R.id.rc_guide,
            KEY_EVENT_GUIDE
        )
        rcKeySparseArray.put(
            R.id.rc_return,
            KEY_EVENT_RETURN
        )
        rcKeySparseArray.put(
            R.id.rc_sero_rotate_button,
            KEY_EVENT_ROTATE_PANEL
        )
        rcKeySparseArray.put(
            R.id.rc_smart_hub,
            KEY_EVENT_HOME
        )
        rcKeySparseArray.put(
            R.id.rc_0,
            KEY_EVENT_NUMBER_0
        )
        rcKeySparseArray.put(
            R.id.rc_1,
            KEY_EVENT_NUMBER_1
        )
        rcKeySparseArray.put(
            R.id.rc_2,
            KEY_EVENT_NUMBER_2
        )
        rcKeySparseArray.put(
            R.id.rc_3,
            KEY_EVENT_NUMBER_3
        )
        rcKeySparseArray.put(
            R.id.rc_4,
            KEY_EVENT_NUMBER_4
        )
        rcKeySparseArray.put(
            R.id.rc_5,
            KEY_EVENT_NUMBER_5
        )
        rcKeySparseArray.put(
            R.id.rc_6,
            KEY_EVENT_NUMBER_6
        )
        rcKeySparseArray.put(
            R.id.rc_7,
            KEY_EVENT_NUMBER_7
        )
        rcKeySparseArray.put(
            R.id.rc_8,
            KEY_EVENT_NUMBER_8
        )
        rcKeySparseArray.put(
            R.id.rc_9,
            KEY_EVENT_NUMBER_9
        )
        rcKeySparseArray.put(
            R.id.rc_minus,
            KEY_EVENT_MINUS
        )
        rcKeySparseArray.put(
            R.id.rc_pre_ch,
            KEY_EVENT_PRECH
        )
        rcKeySparseArray.put(
            R.id.rc_rewind,
            KEY_EVENT_REWIND
        )
        rcKeySparseArray.put(
            R.id.rc_forward,
            KEY_EVENT_FF
        )
        rcKeySparseArray.put(
            R.id.rc_play_back,
            KEY_EVENT_PLAY_BACK
        )
        rcKeySparseArray.put(
            R.id.touch_layout,
            KEY_EVENT_ENTER
        )
        rcKeySparseArray.put(
            R.id.rc_tpad_left,
            KEY_EVENT_LEFT
        )
        rcKeySparseArray.put(
            R.id.rc_tpad_up,
            KEY_EVENT_UP
        )
        rcKeySparseArray.put(
            R.id.rc_tpad_right,
            KEY_EVENT_RIGHT
        )
        rcKeySparseArray.put(
            R.id.rc_tpad_down,
            KEY_EVENT_DOWN
        )
    }
}