package com.samsung.android.poc.remotecontroller.datastore


const val KEY_WORD: String = "KEY_"
const val KEY_EVENT_VOL_UP: String = KEY_WORD + "VOLUP"
const val KEY_EVENT_VOL_DOWN: String = KEY_WORD + "VOLDOWN"
const val KEY_EVENT_CH_UP: String = KEY_WORD + "CHUP"
const val KEY_EVENT_CH_DOWN: String = KEY_WORD + "CHDOWN"

const val KEY_EVENT_POWER: String = KEY_WORD + "POWER"
const val KEY_EVENT_MUTE: String = KEY_WORD + "MUTE"
const val KEY_EVENT_SOURCE: String = KEY_WORD + "SOURCE"
const val KEY_EVENT_COLOR: String = KEY_WORD + "COLOR"
const val KEY_EVENT_GUIDE: String = KEY_WORD + "GUIDE"
const val KEY_EVENT_RETURN: String = KEY_WORD + "RETURN"
const val KEY_EVENT_ROTATE_PANEL: String = KEY_WORD + "ROTATE_PANEL"
const val KEY_EVENT_HOME: String = KEY_WORD + "HOME"

const val KEY_EVENT_NUMBER_1: String = KEY_WORD + "1"
const val KEY_EVENT_NUMBER_2: String = KEY_WORD + "2"
const val KEY_EVENT_NUMBER_3: String = KEY_WORD + "3"
const val KEY_EVENT_NUMBER_4: String = KEY_WORD + "4"
const val KEY_EVENT_NUMBER_5: String = KEY_WORD + "5"
const val KEY_EVENT_NUMBER_6: String = KEY_WORD + "6"
const val KEY_EVENT_NUMBER_7: String = KEY_WORD + "7"
const val KEY_EVENT_NUMBER_8: String = KEY_WORD + "8"
const val KEY_EVENT_NUMBER_9: String = KEY_WORD + "9"
const val KEY_EVENT_NUMBER_0: String = KEY_WORD + "0"
const val KEY_EVENT_MINUS: String = KEY_WORD + "MINUS"
const val KEY_EVENT_PRECH: String = KEY_WORD + "PRECH"
const val KEY_EVENT_PLAY_BACK: String = KEY_WORD + "PLAY_BACK"
const val KEY_EVENT_REWIND: String = KEY_WORD + "REWIND"
const val KEY_EVENT_FF: String = KEY_WORD + "FF"
const val KEY_EVENT_AMBIENT: String = KEY_WORD + "AMBIENT"
const val KEY_EVENT_LEFT: String = KEY_WORD + "LEFT"
const val KEY_EVENT_UP: String = KEY_WORD + "UP"
const val KEY_EVENT_RIGHT: String = KEY_WORD + "RIGHT"
const val KEY_EVENT_DOWN: String = KEY_WORD + "DOWN"
const val KEY_EVENT_ENTER: String = KEY_WORD + "ENTER"
